// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core"

export {}

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElAlert: typeof import("element-plus/es")["ElAlert"]
    ElAvatar: typeof import("element-plus/es")["ElAvatar"]
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElDialog: typeof import("element-plus/es")["ElDialog"]
    ElFormItem: typeof import("element-plus/es")["ElFormItem"]
    ElIcon: typeof import("element-plus/es")["ElIcon"]
    ElImage: typeof import("element-plus/es")["ElImage"]
    ElInput: typeof import("element-plus/es")["ElInput"]
    ElPageHeader: typeof import("element-plus/es")["ElPageHeader"]
    ElUpload: typeof import("element-plus/es")["ElUpload"]
    RouterLink: typeof import("vue-router")["RouterLink"]
    RouterView: typeof import("vue-router")["RouterView"]
  }
}
